#!/bin/sh
######################################
#
# pi-foos init.d service
#
# Daniel Korel | 2017
#
# Auto Start:
# Ubuntu: /etc/update-rc.d pi-foos defaults
# CentOS: chkconfig statesman on
#
######################################

# Usage: /etc/init.d/pi-foos <start|stop|status>

### BEGIN INIT INFO
# Required-Start:    $local_fs $network $syslog
# Required-Stop:     $local_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
### END INIT INFO

NAME="pi-foos"
RUNAS=root
PIDFILE=/var/run/$NAME.pid

pid_file_exists() {
    [ -f "$PIDFILE" ]
}

get_pid() {
    echo "$(cat "$PIDFILE")"
}

is_running() {
    PID=$(get_pid)
    ! [ -z "$(ps aux | awk '{print $2}' | grep "^$PID$")" ]
}

start() {
  if [ -f $PIDFILE ] ; then
    echo 'Service already running' >&2
    return 1
  fi
  echo 'Starting '$NAME >&2
  cd /home/pi/foos/

  # get new versions if they exit at the remote
  bash /home/pi/foos/update-check.sh
  
  # run the game in background
  python game.py >> /var/log/$NAME.log 2>&1 &
  
  sleep 1;
  echo `ps aux | grep game.py | awk '{print $2}'` > $PIDFILE
  #jobs -p > $PIDFILE
  echo $NAME' started' >&2
}

stop() {
  if [ ! -f "$PIDFILE" ] || ! kill -0 $(cat "$PIDFILE"); then
    echo $NAME' not running' >&2
    return 1
  fi
  echo 'Stopping '$NAME' service...' >&2
  kill -TERM $(cat "$PIDFILE") && rm -f "$PIDFILE"
  echo $NAME' stopped' >&2
}

status() {
  if pid_file_exists
  then
  if is_running
  then
    PID=$(get_pid)
    echo "$NAME running with pid $PID"
  else
    echo "$NAME stopped, but pid file exists"
  fi
  else
    echo "$NAME stopped"
  fi
}


case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  uninstall)
    uninstall
    ;;
  restart)
    stop
    start
    ;;
  status)
    status
    ;;
  *)
    echo "Usage: $0 {start|stop|status|restart}"
esac
